spring:
   jmx.enabled: true
   profiles.active: default
   activemq:
      in-memory: true
      pool.enable: false
   cloud:
      stream:
         bindings:
            receiveCookChannel:
               destination: receive-cook
               binder: activemq
               group: main
               
            finishedReceiveCookChannel:
               destination: finished-receive-cook
               binder: activemq
               producer:
                  requiredGroups: main
            servePayChannel:
               destination: finished-receive-cook
               binder: activemq
               group: main
               
            finishedServePayChannel:
               destination: finished-serve-pay
               binder: activemq
   security:
      user:
         name: admin
         password: admin
   activiti:
      historyLevel: full
      dbHistoryUsed: true
management:
   endpoints:
      enabled-by-default: true
      web:
         exposure:
            include: '*'
      jmx:
         exposure:
            include: '*'
   endpoint:
      info:
         enabled: true
      restart:
         enabled: true
      beans:
         cache:
            time-to-live: 15s