server:
   port: 8088
spring:
   datasource:
      url: jdbc:h2:file:C:/data/BPM_ACTIVITY
      username: sa
      password: sa
      platform: h2
      driver-class-name: org.h2.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
         idle-timeout: 30000
         minimum-idle: 2
         maximum-pool-size: 10
      h2.console:
         enabled: true
         path: h2-console
   jpa:
      hibernate.ddl-auto: update
      show-sql: true
      properties.hibernate.format_sql: true