spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/BPM_ACTIVITY
      username: postgres
      password: 12345!fra
      driver-class-name: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
         idle-timeout: 30000
         minimum-idle: 2
         maximum-pool-size: 10
   jpa:
      hibernate.ddl-auto: update
      show-sql: true
      properties.hibernate.format_sql: true
server:
   port: 8088